[package]
name = "rust-jni-base"
version = "0.1.0"
edition = "2024"
build = "src/build.rs"

[dependencies]
jni = "0.21.1"
windows = {version = "0.62.0", features = ["Win32_System_SystemServices", "Win32_System_Console"]}
chrono = "0.4.42"

[lib]
name = "rust_jni"
crate-type = ["cdylib"]